# Generated by Django 5.0.7 on 2024-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imgurl',
            field=models.URLField(default=1048),
            preserve_default=False,
        ),
    ]
