# Generated by Django 5.0.7 on 2024-08-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipe', '0002_recipe_imgurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('passwd', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='imgurl',
            field=models.URLField(default='https://static-00.iconduck.com/assets.00/404-page-not-found-illustration-512x496-zifaajyp.png'),
        ),
    ]
